version: 2
updates:
  - package-ecosystem: "gomod" # Gestionnaire de dépendances pour Go
    directory: "/" # Emplacement de vos fichiers `go.mod`
    schedule:
      interval: "daily" # Vérification quotidienne des mises à jour
  - package-ecosystem: "docker" # Gestionnaire de dépendances pour Docker
    directory: "/" # Emplacement de vos fichiers Dockerfile
    schedule:
      interval: "daily" # Vérification quotidienne des mises à jour
